/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ming.gcp;

import org.junit.jupiter.api.Test;

class RetryableTest {
    @Test void appHasAGreeting() {
        GCSRetry classUnderTest = new GCSRetry();
    }
}
