# permissions for end users to view cassandras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandra-viewer-role
rules:
- apiGroups:
  - ming.mingliang.me
  resources:
  - cassandras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ming.mingliang.me
  resources:
  - cassandras/status
  verbs:
  - get
