server:
  port: ${HTTPS_PORT:8443}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SERVER_SSL_KEY_STORE:classpath:keystore.jks}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
config1:
  key: name
  value: tom
  child:
    name: andy
    age: 10
config2:
  key: dept
  value: IT
  child:
    name: tim
    age: 12
spring:
  data:
    cassandra:
      keyspace-name: test_keyspace
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
  servlet:
    multipart:
      file-size-threshold: 50MB
      max-file-size: 50MB
      max-request-size: 5MB
cos:
  endpoint: https://s3.us-east.cloud-object-storage.appdomain.cloud
  location: us-east
  access-key: ${COS_ACCESS_KEY:myAccessKey}
  secret-key: ${COS_SECRET_KEY:mySecretKey}
  default-bucket-name: ${COS_BUCKET_NAME:default_bucket}
#  api-key: ${COS_API_KEY:myAccessKey}
#  service-instance-id: ${COS_SERVICE_INSTANCE_ID:myServiceId}
